spring:
 application:
  name: foo-service
 config:
  import: configserver:http://18.206.135.45:8888
 cloud:
  config:
    fail-fast: false
 profiles:
  active: local

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://18.206.135.45:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
      
      
server:
  port: 8083
