host: 18.206.135.45
spring:
 application:
  name: foo-service
 config:
  import: configserver:http://${host}:8888
 cloud:
  config:
    fail-fast: false
 profiles:
  active: local

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    ip-address: ${host}
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
      
      
server:
  port: 8083
  
 

