spring:
 application:
  name: bar-service
 config:
  import: http://localhost:8888
 profiles:
  active: local

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
      
