spring:
 application:
  name: bar-service
 config:
  import: configserver:http://44.223.33.158:8888
 cloud:
  config:
    fail-fast: false
 profiles:
  active: local

  
eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
      
      
server:
  port: 8081
  
