spring:
 application:
  name: config-service
 cloud:
    config:
      server:
        git:
          uri: https://github.com/shijujohn1093/app-configuration.git
          skipSslValidation: true
  

server:
  port: 8888
  

