spring:
 application:
  name: config-service
 cloud:
    config:
      server:
        git:
          uri: https://github.com/shijujohn1093/spring-cloud-sample.git
          skipSslValidation: true
          search-paths: app-configurations
  

server:
  port: 8888
  

